[package]
name = "oauth2_passkey_axum"
version = { workspace = true }
edition = { workspace = true }

[features]
default = ["admin-pages", "optional-pages"]
admin-pages = []
optional-pages = []

[dependencies]
askama = { version = "0.13.0" }
http = { workspace = true }
tracing = { workspace = true }

oauth2_passkey = { workspace = true }

axum = { workspace = true }
axum-extra = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
urlencoding = { workspace = true }

futures = { workspace = true }
chrono = { workspace = true }
chrono-tz = { workspace = true }
