[package]
name = "demo-live"
version = { workspace = true }
edition = { workspace = true }

[features]
default = []
bundled-tls = ["oauth2-passkey-axum/bundled-tls"]

[dependencies]
oauth2-passkey-axum = { path = "../oauth2_passkey_axum", default-features = false, features = ["user-ui", "admin-ui"] }
#oauth2-passkey-axum = "0.2"

askama = { workspace = true }
axum = { workspace = true }
dotenvy = { workspace = true }
http = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
