[package]
name = "demo-custom-login"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
oauth2-passkey-axum = { path = "../oauth2_passkey_axum", default-features = false }

askama = { workspace = true }
axum = { workspace = true }
dotenvy = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
