services:
  pg:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
      POSTGRES_DB: demo
    volumes:
      - ./data:/var/lib/postgresql
#      - ./init.sql:/docker-entrypoint-initdb.d/index.sql
    restart: always
